authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    re_path(r'^confirm/$', authapp.register, name='confirm'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
    re_path(r'^', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),
    re_path(r'^category/(?P<pk>\d+)/(?P<page>\d+)/$', mainapp.category, name='category'),
    re_path(r'^products/$', mainapp.products, name='products'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^contacts/$', mainapp.contacts, name='contacts'),
]

ordersapp/urls.py
from django.urls import re_path
import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),

    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),

    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product (models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return '{} ({})'.format(self.name, self.category.name)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('category', 'name')

mainapp/views.py
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory, Product

columns = [
    {
        'title': 'Our Account',
        'href1': 'Your Account',
        'href2': 'Personal information',
        'href3': 'Addresses',
        'href4': 'Discount',
        'href5': 'Orders history',
        'href6': 'Search Terms'
    },
    {
        'title': 'Our Support',
        'href1': 'Site Map',
        'href2': 'Search Terms',
        'href3': 'Advanced Search',
        'href4': 'Mobile',
        'href5': 'Contact Us',
        'href6': 'Addresses'
    },
]


def get_hot_product():
    return random.choice(Product.objects.filter(is_active=True))


def get_same_product(hot_product):
    return hot_product.category.product_set.filter(is_active=True).exclude(pk=hot_product.pk)[:3]


def index(request):
    content = {
        'title': 'Home',
        'columns': columns,
    }
    return render(request, 'mainapp/index.html', content)


def category(request, pk, page=1):
    if int(pk) == 0 or int(pk) == 1:
        category = {
            'pk': 1,
            'name': 'все товары',
        }
        products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = category.product_set.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

    paginator = Paginator(products, 2)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    content = {
        'title': 'Products',
        'category': category,
        'products': products_paginator,
        'columns': columns,
    }
    return render(request, 'mainapp/products_list.html', content)


def products(request):
    hot_product = get_hot_product()
    same_products = get_same_product(hot_product)

    content = {
        'title': 'Products',
        'hot_product': hot_product,
        'same_products': same_products,
        'columns': columns,
    }
    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    content = {
        'title': 'Product',
        'object': get_object_or_404(Product, pk=pk),
        'columns': columns,
    }
    return render(request, 'mainapp/product.html', content)


def contacts(request):
    content = {
        'title': 'Contacts',
        'columns': columns,
    }
    return render(request, 'mainapp/contacts.html', content)

mainapp/templates/mainapp/includes/inc__category_menu.html
<div class="link-menu">
    {% for category in links_menu %}
        <a href="{% url 'main:category' category.pk 1 %}"
           class="{% if request.resolver_match.kwargs.pk == category.pk %}active{% endif %}">
            {{ category.name }}
        </a>
    {% endfor %}
</div>

mainapp/templates/mainapp/includes/inc__main_menu.html
{% load staticfiles %}

<div class="mainMenu">
    <img class="logo" src="{% static 'img/logo.png' %}" alt="logo">
    <span class="shopName">Chromesthesia</span>
    <ul class="socialButtons">
        <li><a href="#">
            <i class="fab fa-facebook-f"></i>
        </a></li>
        <li><a href="#">
            <i class="fab fa-twitter"></i>
        </a></li>
        <li><a href="#">
            <i class="fab fa-youtube"></i>
        </a></li>
        <li><a href="#">
            <i class="fab fa-pinterest-p"></i>
        </a></li>
        <li><a href="#">
            <i class="fab fa-instagram"></i>
        </a></li>
    </ul>
    <ul class="menu">
        <li>
            <a href="{% url 'main:index' %}"
               class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
                <b>Home</b>
            </a>
        </li>
        <li>
            <a href="{% url 'main:products' %}"
               class="{% if request.resolver_match.url_name == 'products' or request.resolver_match.url_name == 'category'%}active{% endif %}">
                <b>Products</b>
            </a>
        </li>
        <li>
            <a href="{% url 'main:contacts' %}"
               class="{% if request.resolver_match.url_name == 'contacts' %}active{% endif %}">
                <b>Contacts</b>
            </a>
        </li>
        {% if user.is_authenticated %}
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href ="" data-toggle="dropdown">
                        {{ user.first_name|default:'Guest' }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'auth:update' %}">
                                профиль
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'ordersapp:orders_list' %}">
                                заказы
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        {% endif %}

        {% if user.is_superuser %}
            <li>
                <a href="{% url 'myadmin:index' %}">Admin</a>
            </li>
        {% endif %}



        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">logout</a>
            {% else %}
                <a href="{% url 'auth:login' %}">login</a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:index' %}" class="basket">
        <span>
            {% if basket %}
                {{ basket.0.get_total_cost|floatformat:0 }} руб
                ({{ basket.0.get_total_quantity }} шт)
             {% endif %}
        </span>
    </a>
</div>