adminapp/urls.py
from django.urls import re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^$', adminapp.UsersListView.as_view(), name='index'),
    re_path(r'^shopuser/create/$', adminapp.ShopuserCreateView.as_view(), name='shopuser_create'),
    re_path(r'^shopuser/update/(?P<pk>\d+)/$', adminapp.ShopuserUpdateView.as_view(), name='shopuser_update'),
    re_path(r'^shopuser/delete/(?P<pk>\d+)/$', adminapp.shopuser_delete, name='shopuser_delete'),

    re_path(r'^productcategories/$', adminapp.CategoriesListView.as_view(), name='categories'),
    re_path(r'^productcategory/create/$', adminapp.ProductCategoryCreateView.as_view(), name='productcategory_create'),
    re_path(r'^productcategory/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='productcategory_update'),
    re_path(r'^productcategory/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='productcategory_delete'),

    re_path(r'^products/(?P<pk>\d+)/$', adminapp.ProductsListView.as_view(), name='products'),
    re_path(r'^product/create/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    re_path(r'^product/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(), name='product_read'),
    re_path(r'^product/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    re_path(r'^product/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    re_path(r'^confirm/$', authapp.register, name='confirm'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
    re_path(r'^', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from authapp.models import ShopUser
from django import forms
from mainapp.models import ProductCategory, Product


class ShopUserCreationAdminForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'age')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserUpdateAdminForm(UserChangeForm):
    class Meta:
        model = ShopUser
        # fields = '__all__'
        fields = ('username', 'first_name', 'last_name', 'email',
                  'age', 'avatar', 'password', 'is_superuser', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

adminapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse, reverse_lazy

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator

from adminapp.forms import ShopUserCreationAdminForm, ShopUserUpdateAdminForm, \
                           ProductCategoryEditForm, ProductEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/index.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'admin/users'
        return context


class CategoriesListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/productcategory_list.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'admin/categories'
        return context


class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/product_list.html'

    def get_queryset(self):
        pk = self.kwargs.get('pk')

        if int(pk) == 0 or int(pk) == 1:
            self.category = {
                'pk': 1,
                'name': 'все товары'
            }
            object_list = Product.objects.all().order_by('-is_active')
        else:
            self.category = get_object_or_404(ProductCategory, pk=pk)
            object_list = self.category.product_set.filter(category__pk=pk).order_by('-is_active')

        return object_list

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['title'] = 'admin/products'
        context['category'] = self.category
        return context


class ShopuserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/shopuser_update.html'
    success_url = reverse_lazy('myadmin:index')
    form_class = ShopUserCreationAdminForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'users/create'
        return context


class ShopuserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/shopuser_update.html'
    success_url = reverse_lazy('myadmin:index')
    form_class = ShopUserUpdateAdminForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'users/update'
        return context


def shopuser_delete(request, pk):
    object = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        # object.delete()
        # вместо удаления лучше сделаем неактивным
        object.is_active = False
        object.save()
        return HttpResponseRedirect(reverse('myadmin:index'))

    content = {
        'title': 'users/delete',
        'user_to_delete': object
    }
    return render(request, 'adminapp/shopuser_delete.html', content)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/productcategory_update.html'
    success_url = reverse_lazy('myadmin:categories')
    # fields = '__all__'
    form_class = ProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'categories/create'
        return context


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/productcategory_update.html'
    success_url = reverse_lazy('myadmin:categories')
    form_class = ProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'categories/update'
        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/productcategory_delete.html'
    success_url = reverse_lazy('myadmin:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'categories/delete'
        return context


def product_create(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        form = ProductEditForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:products', kwargs={'pk': pk}))
    else:
        form = ProductEditForm(initial={'category': category})

    content = {
        'title': 'products/create',
        'form': form,
        'category': category
    }
    return render(request, 'adminapp/product_update.html', content)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'products/read'
        return context


def product_update(request, pk):
    product_object = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        form = ProductEditForm(request.POST, request.FILES, instance=product_object)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:products', kwargs={'pk': product_object.category.pk}))
    else:
        form = ProductEditForm(instance=product_object)

    content = {
        'title': 'products/update',
        'form': form,
        'category': product_object.category
    }
    return render(request, 'adminapp/product_update.html', content)


def product_delete(request, pk):
    object = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        object.is_active = False
        object.save()
        return HttpResponseRedirect(reverse('myadmin:products', kwargs={'pk': object.category.pk}))

    content = {
        'title': 'products/delete',
        'object': object,
        'category': object.category
    }
    return render(request, 'adminapp/product_delete.html', content)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}

</head>

<body>
    <div class="container">
        <div class="admin-container">
            <div class="h2 text-center head">
                Admin
            </div>
        {% block menu %}
            <div class="admin-menu">
                {% include 'adminapp/includes/inc__menu.html' %}
            </div>
        {% endblock %}

        {% block container %}
        {% endblock %}

        </div>
    </div>

</body>
</html>

adminapp/templates/adminapp/index.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}


{% block container %}
    <a href="{% url 'myadmin:shopuser_create' %}"
       class="btn btn-primary new-user">
        новый пользователь
    </a>
    <div class="users-list">
        {% for object in object_list %}
            <div class="user-record {% if not object.is_active %}not-active{% endif %}">
                <div class="img-for-object">
                    <img src="{{ object.avatar|media_folder_users }}"
                     alt="{{ object.username }}">
                </div>
                <div class="user-role">
                    {% if object.is_superuser %}администратор{% else %}пользователь{% endif %}
                    <a href="{% url 'myadmin:shopuser_update' object.pk %}" class="btn btn-success">
                        редактировать
                    </a>
                    <a href="{% url 'myadmin:shopuser_delete' object.pk %}" class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="user-name">
                    <p><strong>{{ object.username }}</strong></p>
                    <p>
                        {% if object.first_name %}
                            <b>{{ object.first_name|title }}</b>
                            {% if object.last_name %}
                                <p>{{ object.last_name|title }}</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                <div class="user-age">
                    age:<br>
                    {{ object.age }} лет
                </div>
                <div class="user-email">
                    email:<br>
                    {{ object.email }}
                </div>
                <div class="user-lastlogin">
                    logged:<br>
                    {{ object.last_login }}
                </div>
            </div>
        {% endfor%}
    </div>

{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="product-delete">
        Уверены, что хотите удалить <b>{{ object.name }}</b>?
        <div class="del-user">
            <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
            </form>
            <a href="{% url 'myadmin:products' category.pk %}" class="btn btn-success">
                отмена
            </a>
        </div>

    </div>
{% endblock %}

adminapp/templates/adminapp/product_list.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}


{% block container %}
    <a href="{% url 'myadmin:product_create' category.pk %}"
       class="btn btn-primary new-product">
        новый продукт
    </a>
    <div class="products-list">
        {% for object in object_list %}
            <div class="product-record {% if not object.is_active %}not-active{% endif %}">
                <img src="{{ object.image|media_folder_products }}"
                     alt="{{ object.name }}">
                <div class="product-name">
                    {{ object.name|title }}
                </div>
                <div class="product-actions">
                    <a href="{% url 'myadmin:product_read' object.pk %}"
                       class="btn btn-info">
                        подробнее
                    </a>
                    <a href="{% url 'myadmin:product_update' object.pk %}"
                       class="btn btn-success">
                        редактировать
                    </a>
                    <a href="{% url 'myadmin:product_delete' object.pk %}"
                       class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                    <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
            </div>
        {% endfor%}
    </div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}

{% block container %}
    <div class = "product-read">
        <img src ="{{ object.image|media_folder_products }}"
             alt = "{{ object.name }}">
        <div class = "product-name">
            Продукт:<br>{{ object.category.name|title }} / {{ object.name|title }}

        </div>
        <div class = "summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <a href = "{% url 'myadmin:product_update' object.pk %}"
                   class="btn btn-primary">
                    редактировать
                </a>
            </p>
            <p>
                <a href = "{% url 'myadmin:product_delete' object.pk %}"
                   class="btn btn-danger">
                    удалить
                </a>
            </p>
            <p>
                <a href = "{% url 'myadmin:products' object.category.pk %}"
                   class="btn btn-success">
                    назад
                </a>
            </p>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="new-product-form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'myadmin:products' category.pk %}"
           class="btn btn-primary form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}

adminapp/templates/adminapp/productcategory_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user-delete">
        Уверены, что хотите удалить <b>{{ object.name }}</b>?
        <div class="del-user">
            <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
            </form>
            <a href="{% url 'myadmin:categories' %}" class="btn btn-success">
                отмена
            </a>
        </div>

    </div>
{% endblock %}

adminapp/templates/adminapp/productcategory_list.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block container %}
    <a href="{% url 'myadmin:productcategory_create' %}"
       class="btn btn-primary new-category">
        новая категория
    </a>
    <div class="categories-list">
        {% for object in object_list %}
            <div class="category-record {% if not object.is_active %}not-active{% endif %}">
                <div class="category-name">
                    {{ object.name|title }}
                </div>
                <div class="category-actions">
                    <a href="{% url 'myadmin:products' object.pk %}"
                       class="btn btn-info">
                        товары категории
                    </a>
                    <a href="{% url 'myadmin:productcategory_update' object.pk %}"
                       class="btn btn-success">
                        редактировать
                    </a>
                    <a href="{% url 'myadmin:productcategory_delete' object.pk %}"
                       class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="category-desc">
                    {{ object.description }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/productcategory_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="new-category-form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'myadmin:categories' %}"
           class="btn btn-primary form-control last">
            к списку категорий
        </a>
    </div>
{% endblock %}

adminapp/templates/adminapp/shopuser_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user-delete">
        Уверены, что хотите удалить <b>{{ user_to_delete.username }}
        {% if user_to_delete.first_name %}
            ({{ user_to_delete.first_name|title }}
                {% if user_to_delete.last_name %}
                    {{ user_to_delete.last_name|title }}
                {% endif %})
        {% endif %}</b>?
        <div class="del-user">
            <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
            </form>
            <a href="{% url 'myadmin:index' %}" class="btn btn-success">
                отмена
            </a>
        </div>

    </div>
{% endblock %}

adminapp/templates/adminapp/shopuser_update.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block menu %}
{% endblock %}

{% block container %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <a href="{% url 'myadmin:index' %}"
       class="btn btn-primary form-control last">
        к списку пользователей
    </a>

{% endblock %}