authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    re_path(r'^confirm/$', authapp.register, name='confirm'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import re_path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    re_path(r'^$', basketapp.index, name='index'),
    re_path(r'^add/(?P<pk>\d+)/$', basketapp.add, name='add'),
    re_path(r'^remove/(?P<pk>\d+)/$', basketapp.remove, name='remove'),
    re_path(r'^update/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.update),
]

geekshop/urls.py
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
    re_path(r'^', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),
    re_path(r'^category/(?P<pk>\d+)/(?P<page>\d+)/$', mainapp.category, name='category'),
    re_path(r'^products/$', mainapp.products, name='products'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^contacts/$', mainapp.contacts, name='contacts'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product (models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return '{} ({})'.format(self.name, self.category.name)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('category', 'name')

mainapp/views.py
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory, Product

columns = [
    {
        'title': 'Our Account',
        'href1': 'Your Account',
        'href2': 'Personal information',
        'href3': 'Addresses',
        'href4': 'Discount',
        'href5': 'Orders history',
        'href6': 'Search Terms'
    },
    {
        'title': 'Our Support',
        'href1': 'Site Map',
        'href2': 'Search Terms',
        'href3': 'Advanced Search',
        'href4': 'Mobile',
        'href5': 'Contact Us',
        'href6': 'Addresses'
    },
]


def get_hot_product():
    return random.choice(Product.objects.filter(is_active=True))


def get_same_product(hot_product):
    return hot_product.category.product_set.filter(is_active=True).exclude(pk=hot_product.pk)[:3]


def index(request):
    content = {
        'title': 'Home',
        'columns': columns,
    }
    return render(request, 'mainapp/index.html', content)


def category(request, pk, page=1):
    if int(pk) == 0 or int(pk) == 1:
        category = {
            'pk': 1,
            'name': 'все товары',
        }
        products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = category.product_set.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

    paginator = Paginator(products, 2)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    content = {
        'title': 'Products',
        'category': category,
        'products': products_paginator,
        'columns': columns,
    }
    return render(request, 'mainapp/products_list.html', content)


def products(request):
    hot_product = get_hot_product()
    same_products = get_same_product(hot_product)

    content = {
        'title': 'Products',
        'hot_product': hot_product,
        'same_products': same_products,
        'columns': columns,
    }
    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    content = {
        'title': 'Product',
        'object': get_object_or_404(Product, pk=pk),
        'columns': columns,
    }
    return render(request, 'mainapp/product.html', content)


def contacts(request):
    content = {
        'title': 'Contacts',
        'columns': columns,
    }
    return render(request, 'mainapp/contacts.html', content)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}
                Chromesthesia / {{ title|default:"page"|title }}
            {% endblock %}
        </title>
        {% block css %}
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {% endblock %}

        {% block js %}
            <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
            <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% endblock %}
    </head>

    <body>
        {% block header %}
        {% endblock %}

        {% block content %}
        {% endblock %}

        {% block container %}
        {% endblock %}

        <div class="footer">
            <div class="container footerUpWrapper">
                {% if columns %}
                    {% for col in columns %}
                        <div class="footerColumn">
                            <div class="headColumn">
                                {{ col.title }}
                            </div>
                            <div class="textColumn">
                                <a href="#">{{ col.href1 }}</a>
                                <a href="#">{{ col.href2 }}</a>
                                <a href="#">{{ col.href3 }}</a>
                                <a href="#">{{ col.href4 }}</a>
                                <a href="#">{{ col.href5 }}</a>
                                <a href="#">{{ col.href6 }}</a>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <b>Server Error. Try Later</b>
                {% endif %}
                <div class="footerColumn newsLetter">
                    <div class="headColumn">
                        Newsletter
                    </div>
                    <div class="columnNewsLetter">
                        <div class="textNewsLetter">
                            Join thousands of other people subs-<br>
                            cribe to our news
                        </div>
                        <input type="email" placeholder="insert email">
                        <button>SUBMIT</button>
                        <div class="payCards">
                            <img src="{% static 'img/payCards/aex.png' %}" alt="">
                            <img src="{% static 'img/payCards/mastercard.png' %}" alt="">
                            <img src="{% static 'img/payCards/maestero.png' %}" alt="">
                            <img src="{% static 'img/payCards/paypal.png' %}" alt="">
                            <img src="{% static 'img/payCards/discover.png' %}" alt="">
                            <img src="{% static 'img/payCards/visa_straight.png' %}" alt="">
                        </div>
                    </div>
                </div>
                <div class="footerColumn aboutUs">
                    <div class="headColumn">
                        About Us
                    </div>
                    <div class="columnAboutUs">
                        <div class="textAboutUs">
                            Lorem ipsum dolor sit amet,
                            consectetuer adipiscing elit. Cum sociis
                            natoque penatibus et magnis dis parturient
                            montes, nascetur ridiculus mus. Donec
                            quam felis, ultricies nec, pellentesque eu,
                            pretium quis, sem.
                        </div>
                        <div class="phone">
                            Phone: 1-999-342-9876
                        </div>
                        <div class="mail">
                            e-mail: info@chromesthesia.com
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footerDown">
            <div class="container footerDownWrapper">
                <div class="allRights">
                     &copy; 2019  CHROMESTHESIA. All rights reserved.
                </div>
                <div class="socialIcons">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-pinterest-p"></i>
                    <i class="fab fa-google-plus"></i>
                    <i class="fab fa-tumblr-square"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-feed"></i>
                </div>
            </div>
        </div>
    </body>
</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

<body>

    {% block header %}
        <div class="header">
            <div class="container headerWrapper">
                {% include 'mainapp/includes/inc__main_menu.html' %}
            </div>
        </div>
    {% endblock %}

    {% block content %}
        <div class="content">
        <div class="container contentWrapper">
            <form action="contacts.html" method="post">
                <fieldset>
                    <legend>write to us</legend>
                    <input type="text" placeholder="Enter your name"><br>
                    <input class="email" type="email" placeholder="Enter your email"><br>
                    <input type="text" placeholder="Message subject"><br>
                    <label class="labelInContacts" for="msg">The essence of your letter:</label><br>
                    <textarea id="msg" name="textareaContent"></textarea><br>
                    <button class="btn">send</button>
                </fieldset>
            </form>
            <div class="addressForm">
                <h2>Address</h2>
                <div class="address">
                    <b>Phone:</b> +7(812)000-11-22<br>
                    <b>Address:</b> St. Petersburg, Moika Emb, 32<br>
                    <b>Email:</b> сhromesthesia@shop.com
                </div>
            </div>
            <div class="map">
                <script async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Aea59ab81fda119f09b6e6e5eb5ceac667dc6ad47b675cab5fe52bdd452e22a27&amp;width=100%25&amp;height=374&amp;lang=ru_RU&amp;scroll=true"></script>
            </div>
        </div>
    </div>
    {% endblock %}
</body>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

<body>
{% block header %}
    <div class="header">
        <div class="headerIndex">
            <div class="container headerWrapper">
                {% include 'mainapp/includes/inc__main_menu.html' %}
                <div class="drDre">
                    <div class="drDreHeader">
                        Beats by Dr.Dre(Beats)
                    </div>
                    <div class="drDreText">
                        the leading brand in the music world created by dr.Dre and Jimmy Iovine in 2006.
                        The company produces the best headband headphones, in-ear headphones and speakers.
                        The main difference between Beats products is the amazing sound quality.
                    </div>
                </div>
                <div class="companyBeats">
                    The company Beats brought listening to music on a whole new level.
                    Now music lovers around the world can feel the emotions,
                    energy and excitement that the musicians experienced in the recording studio.
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}

<body>

    {% block header %}
        <div class="header">
            <div class="container headerWrapper">
                {% include 'mainapp/includes/inc__main_menu.html' %}
            </div>
        </div>
    {% endblock %}

    {% block content %}
        <div class="content">
            <div class="container contentWrapper">
                {% include 'mainapp/includes/inc__category_menu.html' %}
                <div class="details-products">

                    <div class="choiceProduct">

                        <div class="productItem">
                            <a href="{% url 'main:product' object.pk %}">
                                <img src="{{ object.image|media_folder_products }}" alt="{{ object.name }}">
                            </a>
                        </div>

                        <div class="choiceProduct-text">
                            <div class="sale-block">
                                <h3><span>{{ object.name }}</span></h3>
                            </div>
                            <h2>Качество звука на новом уровне.</h2>
                            <h2 class="choicePrice">{{ object.price }} ₽</h2>
                            <a href="{% url 'basket:add' object.pk %}" class="button">В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

</body>

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}

<body>

    {% block header %}
        <div class="header">
            <div class="container headerWrapper">
                {% include 'mainapp/includes/inc__main_menu.html' %}
            </div>
        </div>
    {% endblock %}

    {% block content %}
        <div class="content">
            <div class="container contentWrapper">
                {% include 'mainapp/includes/inc__category_menu.html' %}

                <div class="details-products">

                    <div class="hotProduct">

                        <div class="productItem">
                            <a href="{% url 'main:product' hot_product.pk %}">
                                <img src="{{ hot_product.image|media_folder_products }}" alt="{{ hot_product.name }}">
                            </a>
                        </div>

                        <div class="hotProduct-text">
                            <div class="sale-block">
                                <h3><span>Горячее предложение</span></h3>
                            </div>
                            <h2>{{ hot_product.name }}</h2>
                            <h2 class="hotPrice">{{ hot_product.price }} ₽</h2>
                            <a href="{% url 'basket:add' hot_product.pk %}" class="button">В корзину</a>
                        </div>
                    </div>
                    <div class="sameProducts">
                        <div class="sameProducts-text">
                            <h2>Похожие товары</h2>
                        </div>

                        <div class="sameProducts-wrap">
                            {% for item in same_products %}
                                <div class="productItem same-product">
                                    <a href="{% url 'main:product' item.pk %}">
                                        <img src="{{ item.image|media_folder_products }}" alt="{{ item.name }}">
                                    </a>
                                    <div class="productList">
                                        <h3>{{ item.name }}</h3>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>

                    </div>

                </div>

            </div>
        </div>
    {% endblock %}
</body>

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}


<body>

    {% block header %}
        <div class="header">
            <div class="container headerWrapper">
                {% include 'mainapp/includes/inc__main_menu.html' %}
            </div>
        </div>
    {% endblock %}

    {% block content %}
        <div class="content">
            <div class="container contentWrapper">
                {% include 'mainapp/includes/inc__category_menu.html' %}

                <div class="products_list">
                    <div class="title clearfix">
                        <h2>Категория: "{{ category.name|title }}"</h2>

                        <div class = "paginator">
                            {% if products.has_previous %}
                                <a href = "{% url 'main:category' category.pk products.previous_page_number %}">
                                    <strong><< </strong>
                                </a>
                            {% endif %}
                            <span class = "current">
                                страница {{ products.number }} из {{ products.paginator.num_pages }}
                            </span>
                            {% if products.has_next %}
                                <a href = "{% url 'main:category' category.pk products.next_page_number %}" >
                                    <strong> >></strong>
                                </a>
                            {% endif %}
                        </div>
                    </div>

                    <div class="products">

                        {% for product in products %}
                            <div class="productItem">
                                <a href="{% url 'main:product' product.pk %}">
                                    <img src="{{ product.image|media_folder_products }}" alt="{{ product.name }}">
                                </a>
                                <div class="productList">
                                    <h3>{{ product.name }}</h3>
                                    <span class="price">₽ {{ product.price }}</span>
                                    <a href="{% url 'basket:add' product.pk %}" class="button">В корзину</a>
                                </div>
                            </div>
                        {% endfor %}

                    </div>

                </div>
            </div>
        </div>
    {% endblock %}
</body>